FROM python:3.12-slim

WORKDIR /app

# Install certificates
RUN apt-get update && apt-get install -y ca-certificates

COPY . .

# 🔥 TEMP FIX: bypass SSL verification
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]